# Generated by Django 2.1 on 2018-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
